#pragma once
#include <filesystem>
#include <string>
#include <string_view>
#include <vector>
namespace Localization {
    struct Text {
        const char* key;
        const char* fallback;
        const char* Get(std::string_view language) const;
    };
    struct Language { std::string code, name; };
    std::string NormalizeCode(std::string_view code);
    void Load(const std::filesystem::path& directory = "Data/SKSE/Plugins/FaceLighting/Languages");
    const std::vector<Language>& Languages();
    std::string Resolve(std::string_view requested, std::string_view systemLocale);
    inline constexpr Text dialogueTitle{"dialogueTitle", "Dialogue NPC face light"};
    inline constexpr Text dialogueEnabled{"dialogueEnabled", "Enable dialogue face light###dialogueEnabled"};
    inline constexpr Text dialogueTransition{"dialogueTransition", "Fade in / out###dialogueTransition"};
    inline constexpr Text dialogueDuration{"dialogueDuration", "Transition duration (seconds)###dialogueDuration"};
    inline constexpr Text dialogueInverse{"dialogueInverse", "Inverse-square falloff (CS)###dialogueInverse"};
    inline constexpr Text dialogueLinear{"dialogueLinear", "Linear intensity (CS)###dialogueLinear"};
    inline constexpr Text dialogueRadius{"dialogueRadius", "Light radius###dialogueRadius"};
    inline constexpr Text dialogueIntensity{"dialogueIntensity", "Intensity###dialogueIntensity"};
    inline constexpr Text dialogueX{"dialogueX", "Left / Right (+right)###dialogueX"};
    inline constexpr Text dialogueY{"dialogueY", "Back / Front (+front)###dialogueY"};
    inline constexpr Text dialogueZ{"dialogueZ", "Down / Up (+up)###dialogueZ"};
    inline constexpr Text dialogueHelp{"dialogueHelp", "Lights the dialogue partner in either camera view. Offsets follow the NPC heading."};
    inline constexpr Text title{"title", "Face Lighting"};
    inline constexpr Text padKey{"padKey", "Gamepad shortcut###padKey"};
    inline constexpr Text padModifier{"padModifier", "Gamepad modifier###padModifier"};
    inline constexpr Text padHelp{"padHelp", "Hold the modifier, then press the shortcut. Uses Xbox-style labels; existing game actions are not blocked."};
    inline constexpr Text noModifier{"noModifier", "None"};
    inline constexpr Text modifier{"modifier", "Modifier key###modifier"};
    inline constexpr Text modifierHelp{"modifierHelp", "Hold the modifier, then press the shortcut. Extra modifiers do not match."};
    inline constexpr Text sneakHide{"sneakHide", "Hide player light while sneaking###sneakHide"};
    inline constexpr Text sneakHelp{"sneakHelp", "Restores the enabled state after sneaking. Dialogue lighting is unaffected."};
    inline constexpr Text rangeMode{"rangeMode", "Range mode###rangeMode"};
    inline constexpr Text dialogueRangeMode{"dialogueRangeMode", "Range mode###dialogueRangeMode"};
    inline constexpr Text inverseRadius{"inverseRadius", "Inverse-square radius###inverseRadius"};
    inline constexpr Text dialogueInverseRadius{"dialogueInverseRadius", "Inverse-square radius###dialogueInverseRadius"};
    inline constexpr Text manualRangeHelp{"manualRangeHelp", "Smaller ranges may dim the face near the light's edge."};
    inline constexpr Text csMode{"csMode", "CS integration mode###csMode"};
    inline constexpr Text csModeHelp{"csModeHelp", "Automatic detects compatibility. Manual requires CS to be loaded. Disabled uses regular lighting."};
    inline constexpr Text csManual{"csManual", "CS manual override active."};
    inline constexpr Text csOff{"csOff", "CS integration disabled: regular lighting."};
    inline constexpr Text globalLinear{"globalLinear", "My CS global Linear Lighting is enabled###globalLinear"};
    inline constexpr Text globalLinearHelp{"globalLinearHelp", "Match this to CS global Linear Lighting. Applies to both lights."};
    inline constexpr Text customKey{"customKey", "Custom scan code"};
    inline constexpr Text keyOff{"keyOff", "Off"};
    inline constexpr Text hotkey{"hotkey", "Player light shortcut###hotkey"};
    inline constexpr Text hotkeyHelp{"hotkeyHelp", "Default: L. Toggles and saves player lighting during gameplay."};
    inline constexpr Text temperature{"temperature", "Color temperature###temperature"};
    inline constexpr Text dialogueTemperature{"dialogueTemperature", "Color temperature###dialogueTemperature"};
    inline constexpr Text sectionName{"sectionName", "FaceLighting"};
    inline constexpr Text settingsEntry{"settingsEntry", "Settings"};
    inline constexpr Text basicEntry{"basicEntry", "General"};
    inline constexpr Text playerEntry{"playerEntry", "Player face light"};
    inline constexpr Text npcEntry{"npcEntry", "NPC face light"};
    inline constexpr Text sharedActionsHelp{"sharedActionsHelp", "Actions below apply to all pages."};
    inline constexpr Text saveAll{"saveAll", "Save all settings###save"};
    inline constexpr Text defaultsAll{"defaultsAll", "Restore all defaults###defaults"};
    inline constexpr Text discardAll{"discardAll", "Discard all changes###discard"};
    inline constexpr Text languageHelp{"languageHelp", "Sidebar names update after saving and restarting."};
    inline constexpr Text enabled{"enabled", "Enable player face light###enabled"};
    inline constexpr Text inverse{"inverse", "Inverse-square falloff (CS)###inverse"};
    inline constexpr Text linear{"linear", "Linear light intensity (CS)###linear"};
    inline constexpr Text automatic{"automatic", "Inverse-square mode automatically uses linear lighting."};
    inline constexpr Text linearHelp{"linearHelp", "Requires CS global Linear Lighting."};
    inline constexpr Text radius{"radius", "Light radius###radius"};
    inline constexpr Text intensity{"intensity", "Intensity###intensity"};
    inline constexpr Text range{"range", "Calculated radius (game units): "};
    inline constexpr Text rangeHelp{"rangeHelp", "Range follows intensity; regular radius is preserved."};
    inline constexpr Text right{"right", "Left / Right (+right)###x"};
    inline constexpr Text front{"front", "Back / Front (+front)###y"};
    inline constexpr Text up{"up", "Down / Up (+up)###z"};
    inline constexpr Text placement{"placement", "Follows the player heading. Hidden in first person."};
    inline constexpr Text previewHelp{"previewHelp", "Live preview. Closing discards unsaved changes."};
    inline constexpr Text debug{"debug", "Debug logging###debug"};
    inline constexpr Text save{"save", "Save settings###save"};
    inline constexpr Text defaults{"defaults", "Restore defaults###defaults"};
    inline constexpr Text discard{"discard", "Discard changes###discard"};
    inline constexpr Text empty{"empty", ""};
    inline constexpr Text previewing{"previewing", "Previewing unsaved changes."};
    inline constexpr Text saved{"saved", "Settings saved and applied."};
    inline constexpr Text failed{"failed", "Save failed. Previous settings remain active; check the log."};
    inline constexpr Text restored{"restored", "Defaults selected. Click Save settings to keep them."};
    inline constexpr Text discarded{"discarded", "Unsaved changes discarded."};
    inline constexpr Text csSupported{"csSupported", "CS lighting protocol detected."};
    inline constexpr Text csExperimental{"csExperimental", "CS experimental files detected (Jiaye build baseline)."};
    inline constexpr Text csAbsent{"csAbsent", "CS not loaded: regular lighting fallback."};
    inline constexpr Text csUnsupported{"csUnsupported", "CS version/metadata not recognized: regular lighting fallback."};
    inline constexpr Text csPending{"csPending", "Waiting for Community Shaders detection."};
    inline constexpr Text languageLabel{"languageLabel", "Language###language"};
    inline constexpr Text autoLanguage{"autoLanguage", "Auto (Windows)"};
    inline constexpr Text modeAuto{"modeAuto", "Automatic"};
    inline constexpr Text modeManualEnable{"modeManualEnable", "Manual enable"};
    inline constexpr Text modeDisabled{"modeDisabled", "Disabled"};
    inline constexpr Text modeManual{"modeManual", "Manual"};
    inline constexpr Text shiftKey{"shiftKey", "Shift"};
    inline constexpr Text ctrlKey{"ctrlKey", "Ctrl"};
    inline constexpr Text altKey{"altKey", "Alt"};
    inline constexpr Text padButton1{"padButton1", "D-pad Up"};
    inline constexpr Text padButton2{"padButton2", "D-pad Down"};
    inline constexpr Text padButton3{"padButton3", "D-pad Left"};
    inline constexpr Text padButton4{"padButton4", "D-pad Right"};
    inline constexpr Text padButton5{"padButton5", "Start"};
    inline constexpr Text padButton6{"padButton6", "Back"};
    inline constexpr Text padButton7{"padButton7", "LS"};
    inline constexpr Text padButton8{"padButton8", "RS"};
    inline constexpr Text padButton9{"padButton9", "LB"};
    inline constexpr Text padButton10{"padButton10", "RB"};
    inline constexpr Text padButton11{"padButton11", "A"};
    inline constexpr Text padButton12{"padButton12", "B"};
    inline constexpr Text padButton13{"padButton13", "X"};
    inline constexpr Text padButton14{"padButton14", "Y"};
    inline constexpr Text padButton15{"padButton15", "LT"};
    inline constexpr Text padButton16{"padButton16", "RT"};
    inline constexpr Text diagNotLoaded{"diagNotLoaded", "CommunityShaders.dll: not loaded"};
    inline constexpr Text diagUnavailable{"diagUnavailable", "CommunityShaders.dll: loaded; version information unavailable"};
    inline constexpr Text diagVersion{"diagVersion", "Version match"};
    inline constexpr Text diagMetadata{"diagMetadata", "Metadata match"};
    inline constexpr Text diagMissing{"diagMissing", "missing"};
    inline constexpr Text yes{"yes", "Yes"};
    inline constexpr Text no{"no", "No"};
    inline constexpr Text followHead{"followHead", "Follow bone orientation###followHead"};
    inline constexpr Text dialogueFollowHead{"dialogueFollowHead", "Follow bone orientation###dialogueFollowHead"};
    inline constexpr Text boneHelp{"boneHelp", "Uses head-local X/Y/Z, including pitch and roll. Adjust offsets for your skeleton."};
    inline constexpr Text boneX{"boneX", "Head-local X###x"};
    inline constexpr Text boneY{"boneY", "Head-local Y###y"};
    inline constexpr Text boneZ{"boneZ", "Head-local Z###z"};
    inline constexpr Text dialogueBoneX{"dialogueBoneX", "Head-local X###dialogueX"};
    inline constexpr Text dialogueBoneY{"dialogueBoneY", "Head-local Y###dialogueY"};
    inline constexpr Text dialogueBoneZ{"dialogueBoneZ", "Head-local Z###dialogueZ"};
    inline constexpr Text playerDialogueOn{"playerDialogueOn", "Enable player light when dialogue starts###playerDialogueOn"};
    inline constexpr Text playerDialogueOff{"playerDialogueOff", "Disable player light when dialogue ends###playerDialogueOff"};
    inline constexpr Text playerDialogueHelp{"playerDialogueHelp", "Applies after saving. End option also closes manually enabled light. First-person and sneak hiding still apply."};
    inline constexpr Text selectedTitle{"selectedTitle", "Selected NPCs"};
    inline constexpr Text selectedEnabled{"selectedEnabled", "Enable selected NPC lighting"};
    inline constexpr Text selectedHelp{"selectedHelp", "These settings apply to all selected NPCs. Dialogue lighting takes priority during conversations."};
    inline constexpr Text rosterHelp{"rosterHelp", "Aim at an NPC before opening this menu, or select one in the console first. List changes apply immediately and are stored when you save the game. Up to 32 NPCs per save."};
    inline constexpr Text addCrosshair{"addCrosshair", "Add crosshair target"};
    inline constexpr Text addConsole{"addConsole", "Add console target"};
    inline constexpr Text noTarget{"noTarget", "No valid NPC selected"};
    inline constexpr Text rosterEmpty{"rosterEmpty", "No selected NPCs yet."};
    inline constexpr Text rosterEnabled{"rosterEnabled", "Enabled"};
    inline constexpr Text removeNPC{"removeNPC", "Remove"};
    inline constexpr Text npcLoaded{"npcLoaded", "Loaded"};
    inline constexpr Text npcUnloaded{"npcUnloaded", "Unavailable / unloaded"};
    inline constexpr Text rosterTitle{"rosterTitle", "NPC list"};
    inline constexpr Text sectionLighting{"sectionLighting", "Light & color"};
    inline constexpr Text sectionPosition{"sectionPosition", "Position & tracking"};
    inline constexpr Text sectionBehavior{"sectionBehavior", "Activation & visibility"};
    inline constexpr Text sectionKeys{"sectionKeys", "Keyboard & controller"};
    inline constexpr Text sectionCompatibility{"sectionCompatibility", "Community Shaders"};
    inline constexpr Text sectionPreferences{"sectionPreferences", "Preferences"};
    inline constexpr Text sectionActions{"sectionActions", "Settings"};
    inline constexpr const Text* catalog[]{&selectedTitle,&selectedEnabled,&selectedHelp,&rosterHelp,&addCrosshair,&addConsole,&noTarget,&rosterEmpty,&rosterEnabled,&removeNPC,&npcLoaded,&npcUnloaded,&rosterTitle,&sectionLighting,&sectionPosition,&sectionBehavior,&sectionKeys,&sectionCompatibility,&sectionPreferences,&sectionActions,&playerDialogueOn,&playerDialogueOff,&playerDialogueHelp,&followHead,&dialogueFollowHead,&boneHelp,&boneX,&boneY,&boneZ,&dialogueBoneX,&dialogueBoneY,&dialogueBoneZ,&diagNotLoaded,&diagUnavailable,&diagVersion,&diagMetadata,&diagMissing,&yes,&no,&dialogueTitle,&dialogueEnabled,&dialogueTransition,&dialogueDuration,&dialogueInverse,&dialogueLinear,&dialogueRadius,&dialogueIntensity,&dialogueX,&dialogueY,&dialogueZ,&dialogueHelp,&title,&padKey,&padModifier,&padHelp,&noModifier,&modifier,&modifierHelp,&sneakHide,&sneakHelp,&rangeMode,&dialogueRangeMode,&inverseRadius,&dialogueInverseRadius,&manualRangeHelp,&csMode,&csModeHelp,&csManual,&csOff,&globalLinear,&globalLinearHelp,&customKey,&keyOff,&hotkey,&hotkeyHelp,&temperature,&dialogueTemperature,&sectionName,&settingsEntry,&basicEntry,&playerEntry,&npcEntry,&sharedActionsHelp,&saveAll,&defaultsAll,&discardAll,&languageHelp,&enabled,&inverse,&linear,&automatic,&linearHelp,&radius,&intensity,&range,&rangeHelp,&right,&front,&up,&placement,&previewHelp,&debug,&save,&defaults,&discard,&empty,&previewing,&saved,&failed,&restored,&discarded,&csSupported,&csExperimental,&csAbsent,&csUnsupported,&csPending,&languageLabel,&autoLanguage,&modeAuto,&modeManualEnable,&modeDisabled,&modeManual,&shiftKey,&ctrlKey,&altKey,&padButton1,&padButton2,&padButton3,&padButton4,&padButton5,&padButton6,&padButton7,&padButton8,&padButton9,&padButton10,&padButton11,&padButton12,&padButton13,&padButton14,&padButton15,&padButton16};
}




